runtime: python27
api_version: 1
threadsafe: true
application: cbn-elements
version: 1

handlers:
- url: /$
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /elements/elements.build.html
  static_files: dist/elements/elements.build.html
  upload: dist/elements/elements.build.html
  secure: always

- url: /elements/elements.build.js
  static_files: dist/elements/elements.build.js
  upload: dist/elements/elements.build.js
  secure: always

- url: /catalog.json
  static_files: dist/catalog.json
  upload: dist/catalog.json
  secure: always

- url: /images/
  static_dir: dist/images
  secure: always

- url: /data/
  static_dir: dist/data
  secure: always

- url: /bower_components/
  static_dir: dist/bower_components
  secure: always

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
- ^bower_components.*$
- ^\.idea.*$
- ^\.tmp.*$
